from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DataRequirement:
    key: str
    title: str
    priority: str
    refresh: str
    grain: str
    objective: str
    fields: tuple[str, ...]
    known_sources: tuple[str, ...] = ()
    gaps: tuple[str, ...] = ()


REQUIREMENTS: tuple[DataRequirement, ...] = (
    DataRequirement(
        key="vendas_faturamento",
        title="Vendas e faturamento por item",
        priority="prioridade_1",
        refresh="diaria",
        grain="uma linha por item de nota fiscal ou item vendido",
        objective=(
            "Medir vendas, toneladas, faturamento, preco medio, margem, mix, cliente, "
            "vendedor, regiao, segmento e produto."
        ),
        known_sources=("D0A4D301", "0F75E84D", "CAF55C1D", "drive:margem_resumo_latest"),
        fields=(
            "Data do pedido",
            "Data de faturamento/emissao",
            "Numero do pedido",
            "Numero da nota fiscal",
            "Empresa/unidade",
            "Deposito",
            "Codigo do cliente",
            "CNPJ/CPF",
            "Razao social/nome fantasia",
            "Cidade",
            "UF",
            "CEP",
            "Segmento/grupo do cliente",
            "Vendedor",
            "Regiao comercial",
            "Codigo/SKU do produto",
            "Descricao do produto",
            "Familia",
            "Grupo",
            "Subgrupo",
            "Classe",
            "Quantidade",
            "Peso em kg",
            "Preco unitario",
            "Preco por kg",
            "Valor bruto",
            "Descontos",
            "Impostos",
            "Receita liquida",
            "Frete",
            "Tipo de frete",
            "Condicao de pagamento",
            "Prazo medio de pagamento",
            "Custo do produto",
            "Custo por kg",
            "Margem em R$",
            "Margem percentual",
            "Devolucoes/cancelamentos",
        ),
    ),
    DataRequirement(
        key="cotacoes_orcamentos",
        title="Cotacoes e orcamentos",
        priority="prioridade_1",
        refresh="diaria",
        grain="uma linha por item cotado",
        objective=(
            "Medir kg cotados, taxa de conversao, conversao por vendedor, cliente, "
            "regiao, segmento e produto, alem de demanda nao convertida."
        ),
        fields=(
            "Numero do orcamento",
            "Data do orcamento",
            "Codigo do cliente",
            "Cliente",
            "Cidade/UF",
            "Segmento",
            "Vendedor",
            "Regiao",
            "Codigo/SKU do produto",
            "Descricao",
            "Familia",
            "Quantidade",
            "Peso em kg",
            "Preco ofertado",
            "Preco por kg",
            "Valor total",
            "Desconto",
            "Frete",
            "Condicao de pagamento",
            "Validade da proposta",
            "Status do orcamento",
            "Orcamento em aberto",
            "Orcamento aprovado",
            "Orcamento perdido",
            "Orcamento cancelado",
            "Numero do pedido gerado",
            "Data da conversao",
            "Motivo da perda",
            "Concorrente",
            "Preco concorrente",
        ),
        gaps=("Ainda nao ha relatorio de cotacoes/orcamentos identificado no menu capturado.",),
    ),
    DataRequirement(
        key="pedidos_carteira",
        title="Pedidos e carteira",
        priority="prioridade_1",
        refresh="diaria",
        grain="uma linha por item de pedido",
        objective="Acompanhar carteira futura, volume pendente, lead time e demanda contratada ainda nao faturada.",
        known_sources=("D0A4D301", "drive:gestao_producao_latest"),
        fields=(
            "Numero do pedido",
            "Data de entrada",
            "Data de aprovacao",
            "Cliente",
            "Vendedor",
            "Regiao",
            "Produto",
            "Quantidade",
            "Peso em kg",
            "Preco",
            "Condicao de pagamento",
            "Status",
            "Pedido liberado",
            "Pedido bloqueado",
            "Pedido em separacao",
            "Pedido em producao",
            "Pedido faturado",
            "Pedido parcialmente faturado",
            "Saldo pendente",
            "Data prevista de entrega",
            "Data efetiva de entrega",
            "Data de faturamento",
            "Numero da NF",
        ),
        gaps=(
            "Confirmar se D0A4D301 cobre pedidos abertos/parcialmente faturados ou apenas faturamento.",
            "A planilha Gestão da Produção deve ser inspecionada como fonte complementar de carteira/pedido/item.",
        ),
    ),
    DataRequirement(
        key="estoque",
        title="Estoque por produto e unidade",
        priority="prioridade_1",
        refresh="diaria",
        grain="fotografia periodica por produto, unidade, deposito e lote quando existir",
        objective="Calcular giro, cobertura em dias, estoque parado, ruptura, excesso, envelhecimento e reposicao.",
        known_sources=("804C04C1", "6630A54D", "DBF2AB0E", "A6B5B978"),
        fields=(
            "Data da posicao do estoque",
            "Empresa/unidade",
            "Deposito",
            "Codigo/SKU",
            "Descricao",
            "Familia",
            "Grupo",
            "Subgrupo",
            "Quantidade fisica",
            "Peso em kg",
            "Custo medio",
            "Custo por kg",
            "Valor financeiro do estoque",
            "Estoque disponivel",
            "Estoque reservado",
            "Estoque comprometido",
            "Estoque bloqueado",
            "Estoque em transito",
            "Lote",
            "Data da ultima entrada",
            "Data da ultima saida",
            "Data da ultima compra",
        ),
        gaps=(
            "Base operacional coberta por 804C04C1, 6630A54D e DBF2AB0E; "
            "A6B5B978 foi validado sem registros/colunas no cenario atual.",
            "Confirmar se todos os campos financeiros de estoque, lote e datas de ultima movimentacao existem nas colunas retornadas.",
        ),
    ),
    DataRequirement(
        key="compras_fornecedores",
        title="Compras por fornecedor e produto",
        priority="prioridade_2",
        refresh="diaria ou semanal",
        grain="uma linha por item de pedido de compra ou nota de entrada",
        objective="Conectar compra, estoque, venda e margem; acompanhar custo de aquisicao e fornecedores.",
        fields=(
            "Numero do pedido de compra",
            "Data do pedido",
            "Fornecedor",
            "CNPJ do fornecedor",
            "Codigo/SKU",
            "Descricao",
            "Familia",
            "Quantidade",
            "Peso em kg",
            "Preco unitario",
            "Preco por kg",
            "Valor total",
            "Frete",
            "Condicao de pagamento",
            "Prazo de pagamento",
            "Data prevista de entrega",
            "Data efetiva de recebimento",
            "Quantidade recebida",
            "Saldo pendente",
            "Empresa/unidade",
            "Deposito",
            "Status do pedido de compra",
            "Nota fiscal de entrada",
        ),
        gaps=("Nenhum relatorio claro de compras apareceu nos 13 relatorios capturados.",),
    ),
    DataRequirement(
        key="cadastro_produtos",
        title="Cadastro completo de produtos",
        priority="prioridade_1",
        refresh="semanal/mensal",
        grain="uma linha por SKU/produto",
        objective="Enriquecer analises por familia, atributos tecnicos e NCM para futuro cruzamento com comercio exterior.",
        known_sources=("6AD70B15", "drive:gestao_producao_latest", "drive:margem_resumo_latest"),
        fields=(
            "Codigo/SKU",
            "Descricao",
            "Descricao comercial",
            "Familia",
            "Grupo",
            "Subgrupo",
            "Classe",
            "Marca",
            "Unidade de medida",
            "Peso unitario",
            "Espessura",
            "Largura",
            "Comprimento",
            "Bitola",
            "Qualidade",
            "Norma",
            "Material",
            "NCM",
            "Origem",
            "Status ativo/inativo",
        ),
        gaps=(
            "Ainda falta relatorio cadastral completo de produtos; 6AD70B15 cobre estrutura/BOM, nao cadastro completo.",
            "A planilha Gestão da Produção traz item do PA/MP por pedido; a planilha de margem traz Apoio, BD_Meta e Tabela de Preço para atributos operacionais de produto/SKU.",
        ),
    ),
    DataRequirement(
        key="cadastro_clientes",
        title="Cadastro completo de clientes",
        priority="prioridade_1",
        refresh="semanal/mensal",
        grain="uma linha por cliente",
        objective="Analisar carteira, concentracao, recorrencia, potencial, reativacao, regiao e segmento.",
        known_sources=("027051BD", "D0A4D301"),
        fields=(
            "Codigo do cliente",
            "CNPJ/CPF",
            "Razao social",
            "Nome fantasia",
            "Endereco",
            "CEP",
            "Cidade",
            "UF",
            "Telefone",
            "E-mail",
            "Segmento/grupo do cliente",
            "CNAE",
            "Vendedor responsavel",
            "Regiao comercial",
            "Data de cadastro",
            "Data da primeira compra",
            "Data da ultima compra",
            "Limite de credito",
            "Condicao de pagamento padrao",
            "Situacao ativo/inativo",
        ),
    ),
    DataRequirement(
        key="devolucoes_cancelamentos",
        title="Devolucoes e cancelamentos",
        priority="prioridade_2",
        refresh="diaria",
        grain="uma linha por item devolvido ou cancelado",
        objective="Medir perdas comerciais e operacionais.",
        known_sources=("D0A4D301",),
        fields=(
            "Data",
            "Cliente",
            "Pedido",
            "Nota fiscal",
            "Produto",
            "Quantidade",
            "Peso",
            "Valor",
            "Motivo da devolucao",
            "Motivo do cancelamento",
            "Vendedor",
            "Regiao",
        ),
        gaps=("Confirmar se os motivos existem em modulo/tabela propria ou em relatorio separado.",),
    ),
    DataRequirement(
        key="financeiro_recebiveis",
        title="Financeiro e recebiveis",
        priority="prioridade_2",
        refresh="diaria",
        grain="uma linha por titulo/parcela ou documento financeiro",
        objective="Cruzar venda, margem, prazo e qualidade financeira do cliente.",
        known_sources=("37D9E431",),
        fields=(
            "Pedido",
            "Cliente",
            "Data da venda",
            "Valor faturado",
            "Vencimento",
            "Data de pagamento",
            "Dias de atraso",
            "Valor em aberto",
            "Status",
            "Inadimplencia",
            "Prazo medio real",
        ),
        gaps=("37D9E431 esta depriorizado, mas deve voltar quando a base comercial estiver coberta.",),
    ),
    DataRequirement(
        key="logistica_frete",
        title="Logistica e frete",
        priority="prioridade_2",
        refresh="diaria",
        grain="uma linha por pedido/entrega/ocorrencia logistica",
        objective="Avaliar rentabilidade comercial considerando custo logistico.",
        known_sources=("C1A4D279", "D0A4D301", "drive:gestao_producao_latest"),
        fields=(
            "Numero do pedido",
            "Cliente",
            "Cidade/UF",
            "Peso",
            "Frete cobrado",
            "Custo do frete",
            "Transportadora",
            "Tipo de entrega",
            "Data prevista",
            "Data de saida",
            "Data de entrega",
            "Distancia ou rota",
        ),
        gaps=(
            "C1A4D279 cobre ocorrencias.",
            "A planilha Gestão da Produção traz Transportadora, Valor Frete, romaneio e datas logisticas; ainda falta confirmar rota/distancia.",
        ),
    ),
)


EXTRACTION_RULES: tuple[str, ...] = (
    "Preferir CSV ou Excel quando nao houver API/banco disponivel.",
    "Manter uma linha por transacao/item; evitar consolidacoes, totais e subtotais misturados.",
    "Preservar codigos unicos de cliente, produto, pedido e fornecedor.",
    "Manter datas em campos proprios e valores/quantidades em colunas separadas.",
    "Quando um campo nao existir, registrar informacao equivalente, modulo/tabela, relatorio disponivel ou necessidade de consulta especifica.",
    "Nesta etapa, priorizar identificar quais dados ja existem no ERP e como podem ser extraidos.",
)


def requirements_by_source() -> dict[str, tuple[DataRequirement, ...]]:
    index: dict[str, list[DataRequirement]] = {}
    for requirement in REQUIREMENTS:
        for source in requirement.known_sources:
            index.setdefault(source, []).append(requirement)
    return {source: tuple(items) for source, items in index.items()}
